apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: oluwasegun7/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: oluwasegun7/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: oluwasegun7/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: oluwasegun7/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/auth-depl.yaml
      - infra/k8s/auth-mongo-depl.yaml
      - infra/k8s/ingress-srv.yaml
      - infra/k8s/client-depl.yaml
      - infra/k8s/tickets-depl.yaml
      - infra/k8s/tickets-mongo-depl.yaml
      - infra/k8s/nats-depl.yaml
      - infra/k8s/orders-depl.yaml
      - infra/k8s/orders-mongo-depl.yaml
